spring:
    dev_model: true
    
    datasource:
      readSize: 1
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      write:
        url: jdbc:mysql://127.0.0.1:3306/springboot
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
  #     filters: stat
  #     maxActive: 20
  #     initialSize: 1
  #     maxWait: 60000
  #     minIdle: 1
  #     timeBetweenEvictionRunsMillis: 60000
  #     minEvictableIdleTimeMillis: 300000
  #     validationQuery: select 'x'
  #     testWhileIdle: true
  #     testOnBorrow: false
  #     testOnReturn: false
  #     poolPreparedStatements: true
  #     maxOpenPreparedStatements: 20

      read:
        url: jdbc:mysql://127.0.0.1:3306/springboot
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
  #     filters: stat
  #     maxActive: 20
  #     initialSize: 1
  #     maxWait: 60000
  #     minIdle: 1
  #     timeBetweenEvictionRunsMillis: 60000
  #     minEvictableIdleTimeMillis: 300000
  #     validationQuery: select 'x'
  #     testWhileIdle: true
  #     testOnBorrow: false
  #     testOnReturn: false
  #     poolPreparedStatements: true
  #     maxOpenPreparedStatements: 20

    redis:
        database: 0
        host: 127.0.0.1
#        password: foobared
        port: 6379
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 10
            max-wait: -1
            
    mail:
        host: mail.gomeholdings.com
        username: shaotianxiong@gomeholdings.com    
        password: xiong123
        properties:
            mail: 
                smtp:
                    auth: true
                    timeout: 25000
                    
#    rabbitmq:
#        host: 192.168.2.71
#        port: 5672
#        username: hxb
#        password: hxb

    aop:
        proxy-target-class: true
        
            
#指定log的配置文件，以及记录Spring Boot的log级别  
logging:
    config: classpath:logbak.xml
    
    
#Dubbo
#ZooKeeper
#dubbo:
#    registry:
#        address: 192.168.2.72:2181
            